### ISSUE TITLE
配置文件中的push_url怎么用

### ISSUE THREAD

**Issue by rsa-sha2** [qunarcorp/ejabberd-open#47]
配置文件中该字段[push_url](https://github.com/qunarcorp/ejabberd-open/blob/master/ejabberd.yml.qunar#L674)是用来做什么的呢

**Comment by memacs** [comment]
该字段配置的是[推送服务](https://github.com/qunarcorp/push_service_open)提供的接口，ejabberd会把所有的消息通过该接口发给推送服务，推送服务根据业务逻辑，将消息推送给手机客户端。

如果不配置该字段，则ejabberd就不会调用该接口。

自己也可以根据需要提供一个接口，来接受所有的消息，然后做自己的逻辑（比如，将消息放入消息队列等）

**Comment by rsa-sha2** [comment]
谢谢你的回复
