### ISSUE TITLE
配置文件中hosts是做什么用的

### ISSUE THREAD

**Issue by rsa-sha2** [qunarcorp/ejabberd-open#48]
[hosts](https://github.com/qunarcorp/ejabberd-open/blob/master/ejabberd.yml.qunar#L96)配置是用来做什么的呢，可以随时修改吗

**Comment by memacs** [comment]
host是用来标示一个公司或者一个组织的，host的下面会有这个组织的所有成员，一般用该公司的域名来表示，例如[im.ctrip.com](im.ctrip.com)。

host一旦确定后，后面就不要修改了。因为之前的历史消息等内容都是和host有关，修改后，之前的历史就和修改后的对应不上了

**Comment by rsa-sha2** [comment]
谢谢
