### ISSUE TITLE
im的默认域名可以修改吗

### ISSUE THREAD

**Issue by rsa-sha2** [qunarcorp/ejabberd-open#49]
im的默认域名[qtalk.test.org](https://github.com/qunarcorp/ejabberd-open/blob/master/ejabberd.yml.qunar#L97)可以修改吗，修改了后，其它地方也有要修改的吗

**Comment by memacs** [comment]
可以修改，如果修改的话，需要修改多个服务的配置：

* /startalk/ejabberd/etc/ejabberd.yml
```
hosts:
  - "qtalk.test.org"
```
* /startalk/tomcat/im_http_service/webapps/im_http_service/WEB-INF/classes/nav.json
```
    "domain": "qtalk.test.org",
```

**Comment by memacs** [comment]
还需要
