### ISSUE TITLE
postgredql报警解决&pgejabberd配置参考问题

### ISSUE THREAD

**Issue by z991** [qunarcorp/ejabberd-open#75]
ejabberd配置
参考 https://github.com/qunarcorp/ejabberd-open/blob/master/doc/setting.md配置redis后有问题，应该是
sm_db_type: redis
redis_start_mode: 0
redis_pool_size: 1
redis_server: "127.0.0.1"
redis_port: 6379
redis_password: "123456"
redis_tab: "0,1,2,3,5,7,10,11,15"

**Comment by z991** [comment]
根据按照文档，配置文件的位置应该在/export/pg110_data/postgresql.conf. 你检查下logging_collector 是不是配置的off，如果是的话，改为on，然后重启一下数据库
关闭数据库的命令：/opt/pg11/bin/pg_ctl -D /export/pg110_data stop
启动数据库的命令：/opt/pg11/bin/pg_ctl -D /export/pg110_data start

**Comment by z991** [comment]
建议更新下readme.md文件

**Comment by memacs** [comment]
> 
> 
> ejabberd配置
> 参考 [https://github.com/qunarcorp/ejabberd-open/blob/master/doc/setting.md配置redis后有问题，应该是](https://github.com/qunarcorp/ejabberd-open/blob/master/doc/setting.md%E9%85%8D%E7%BD%AEredis%E5%90%8E%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%98%AF)
> sm_db_type: redis
> redis_start_mode: 0
> redis_pool_size: 1
> redis_server: "127.0.0.1"
> redis_port: 6379
> redis_password: "123456"
> redis_tab: "0,1,2,3,5,7,10,11,15"

[setting.md](https://github.com/qunarcorp/ejabberd-open/blob/master/doc/setting.md)文件给的是一个例子，安装步骤中并没有说明需要修改改配置，默认配置是正确的，如果redis不是按照文档安装的，才需要更改该配置。

**Comment by memacs** [comment]
> 
> 
> 根据按照文档，配置文件的位置应该在/export/pg110_data/postgresql.conf. 你检查下logging_collector 是不是配置的off，如果是的话，改为on，然后重启一下数据库
> 关闭数据库的命令：/opt/pg11/bin/pg_ctl -D /export/pg110_data stop
> 启动数据库的命令：/opt/pg11/bin/pg_ctl -D /export/pg110_data start

这个会更新到readme文件中，感谢反馈
