### ISSUE TITLE
客户端一直loading

### ISSUE THREAD

**Issue by dongyuekai** [qunarcorp/ejabberd-open#79]
nginx日志是这样的：
![image](https://user-images.githubusercontent.com/16332837/54502485-d8d6ef80-4965-11e9-9c7e-7c8cf40c1861.png)

**Comment by memacs** [comment]
请贴一下服务器日志

/startalk/ejabberd/var/log/ejabberd/ejabberd.log
/startalk/openresty/nginx/logs/access.log
/startalk/openresty/nginx/logs/error.log

**Comment by dongyuekai** [comment]
（涂鸦处都是我本机的ip地址）
ejabberd日志今天没有最新的打印，我贴一下上周五的：
![image](https://user-images.githubusercontent.com/16332837/54502774-58b18980-4967-11e9-9d8b-73fd7b01506d.png)
nginx的access.log:
![image](https://user-images.githubusercontent.com/16332837/54502858-b219b880-4967-11e9-86b7-4a4fdd90ccac.png)
nginx的error.log:
![image](https://user-images.githubusercontent.com/16332837/54502910-e9886500-4967-11e9-9323-69b21e4d152d.png)
这个是导航的返回值：
![image](https://user-images.githubusercontent.com/16332837/54502693-f6588900-4966-11e9-8efd-fa45ab7be5b5.png)

**Comment by memacs** [comment]
你检查下你得服务器的5202端口是否开启了防火墙，你从别的电脑telnet下这个端口，看是否可以访问到

**Comment by dongyuekai** [comment]
telnet了一下  可以连上

**Comment by memacs** [comment]
需要你把
