### ISSUE TITLE
帮忙看一下这个问题：客户端无法连接始终显示正在验证用户信息

### ISSUE THREAD

**Issue by ren2qiqi** [qunarcorp/ejabberd-open#80]
ejabberd.yml配置
[ejabberd.txt](https://github.com/qunarcorp/ejabberd-open/files/2976109/ejabberd.txt)
ejabberdctl.cfg配置
[ejabberdctl.txt](https://github.com/qunarcorp/ejabberd-open/files/2976110/ejabberdctl.txt)

**Comment by ren2qiqi** [comment]
ejabberd/var/log/ejabberd/ejabberd.log
![image](https://user-images.githubusercontent.com/45489937/54503073-8fd46a80-4968-11e9-8bc3-ac8a2babc34a.png)
/startalk/openresty/nginx/logs/access.log
![image](https://user-images.githubusercontent.com/45489937/54503115-bb575500-4968-11e9-8ed4-9c819b289b3d.png)

/startalk/openresty/nginx/logs/error.log
![image](https://user-images.githubusercontent.com/45489937/54503121-beeadc00-4968-11e9-85c9-4137423d393a.png)

**Comment by memacs** [comment]
你应该用的是电脑端的客户端，你可以先git pull下ejabberd这个项目，看日志你的版本比较老，需要升级ejabberd的代码和配置文件
