### ISSUE TITLE
请问这个项目是如何保证消息必达不丢失的呢？

### ISSUE THREAD

**Issue by iamxvbaba** [qunarcorp/ejabberd-open#81]

**Comment by iamxvbaba** [comment]
想学习一下，我应该看哪块代码

**Comment by memacs** [comment]
1、TCP活着的时候，通过TCP发送消息

**Comment by iamxvbaba** [comment]
> 1、TCP活着的时候，通过TCP发送消息
> 2、客户端重连TCP的时候，用一个时间去拉取TCP断开这段时间的历史
> 
> 细节可以查看客户端得代码
> [imsdk-android](https://github.com/qunarcorp/imsdk-android)

ok,thank you.
