### ISSUE TITLE
如何用sdk创建新帐号

### ISSUE THREAD

**Issue by erikcai** [qunarcorp/ejabberd-open#88]
目前只有admin:testpassword一个测试账号，如何能够用sdk创建startalk聊天系统新帐号？

**Comment by memacs** [comment]
请参考
[用户管理](https://github.com/qunarcorp/ejabberd-open/wiki/%E7%94%A8%E6%88%B7%E7%AE%A1%E7%90%86)

开源版本需要自己使用sql，或者自己编写工具来进行用户管理
