### ISSUE TITLE
安装ejabberd时报错

### ISSUE THREAD

**Issue by xuleiluvmusic** [qunarcorp/ejabberd-open#94]
在make这一部时报错

src/mod_muc_room.erl:5691: syntax error before: '->'
src/mod_muc_room.erl:5687: function do_send_push_message/6 undefined
ERROR: compile failed while processing /startalk/download/ejabberd-open: rebar_abort
make: *** [deps/.built] Error 1

提问的注意事项可以参考：[如何有效地报告 Bug](https://www.jianshu.com/p/84e9b5166991)

**Comment by memacs** [comment]
已修复，新加功能的bug
